import Head from "next/head";

export function HeadComponent(props) {
    return (
        <Head>
            <title>Poc JAMstack app</title>
            <meta name="description" content="Generated by Yurii and Vitalii, 31 Aug 2022 :)"/>
            <link rel="icon" href="/src/public/favicon.ico"/>
        </Head>

    )
}